{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "MRmX8cglaReN",
        "outputId": "864f52ee-b3a0-4819-d71d-483b5dea8163"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)\n",
            "Collecting scikit-learn\n",
            "  Downloading scikit_learn-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.8/10.8 MB\u001b[0m \u001b[31m16.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)\n",
            "Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)\n",
            "Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)\n",
            "Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)\n",
            "Installing collected packages: scikit-learn\n",
            "  Attempting uninstall: scikit-learn\n",
            "    Found existing installation: scikit-learn 1.2.2\n",
            "    Uninstalling scikit-learn-1.2.2:\n",
            "      Successfully uninstalled scikit-learn-1.2.2\n",
            "Successfully installed scikit-learn-1.3.2\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)\n",
            "Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)\n",
            "Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)\n"
          ]
        }
      ],
      "source": [
        "#install and import packages\n",
        "!pip install --upgrade scikit-learn\n",
        "!pip install pandas\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "import sklearn\n",
        "from sklearn.feature_selection import VarianceThreshold\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.preprocessing import Normalizer, StandardScaler, MinMaxScaler, PowerTransformer, MaxAbsScaler, LabelEncoder\n",
        "from sklearn.model_selection import GridSearchCV\n",
        "\n",
        "from sklearn import linear_model, ensemble\n",
        "from sklearn.model_selection import cross_val_score\n",
        "from sklearn import model_selection\n",
        "import numpy\n",
        "\n",
        "from sklearn.preprocessing import OneHotEncoder\n",
        "from sklearn.neighbors import KNeighborsClassifier\n",
        "from sklearn.linear_model import RidgeClassifier\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "from sklearn.model_selection import cross_validate"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#read and display data\n",
        "data = pd.read_csv(\"/content/winequality-red.csv\", sep = \";\")\n",
        "#split into features/target\n",
        "x = data.drop(columns = ['quality'])\n",
        "y = data['quality']"
      ],
      "metadata": {
        "id": "cHounugzr3Cs"
      },
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#define hyperparameter grids for each type of classifier\n",
        "kn_param_grid = GridSearchCV(KNeighborsClassifier(),\n",
        "    param_grid = {\n",
        "        'n_neighbors' : [1, 5, 10, 50, 100],\n",
        "        'algorithm' :  ['ball_tree', 'kd_tree', 'brute'],\n",
        "        'leaf_size' : [1, 5, 10, 50]\n",
        "                }\n",
        "                             )\n",
        "ridge_param_grid = GridSearchCV(RidgeClassifier(),\n",
        "    param_grid = {\n",
        "        'tol' : [.0001, 0.001, 0.01, 0.1],\n",
        "        'solver' : [\"svd\", \"cholesky\",\"sparse_cg\", 'saga', 'lsqr'],\n",
        "        'alpha' : [0.1, 0.2, 0.5, 1.0]\n",
        "                }\n",
        "                                )\n",
        "\n",
        "dt_param_grid = GridSearchCV(DecisionTreeClassifier(),\n",
        "    param_grid = {\n",
        "        'max_depth' : [1,2,5, 10],\n",
        "        'max_features' : [None, \"auto\", \"sqrt\", \"log2\"],\n",
        "        'min_samples_split':[0.1, 0.2, 0.5, 1.0]\n",
        "                }\n",
        "                             )\n",
        "\n",
        "bagging_param_grid = GridSearchCV(estimator = ensemble.BaggingClassifier(), param_grid = {\n",
        "    \"n_estimators\" : [50, 100, 500],\n",
        "    \"max_features\" : [0.1, 1.0, 5]\n",
        "})\n",
        "\n",
        "random_forest_param_grid = {\"n_estimators\" : [100, 500, 1000, 10000],\n",
        "    \"criterion\" : [\"gini\", \"entropy\", \"log_loss\"],\n",
        "    \"max_depth\" : [None, 2, 3, 5, 10]\n",
        "}\n",
        "\n",
        "#construct a pipeline with a scaler, encoder, feature selector, and estimator/classifier\n",
        "pipe = Pipeline([\n",
        "    ('scaler', StandardScaler()),\n",
        "    ('onehot', OneHotEncoder()),\n",
        "    ('selector', VarianceThreshold()),\n",
        "    ('estimator', KNeighborsClassifier())\n",
        "])\n",
        "\n",
        "#train/test split\n",
        "x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.2, random_state=42)\n",
        "\n",
        "#define a grid search over different estimators in the pipeline\n",
        "grid = GridSearchCV(\n",
        "    estimator=pipe,\n",
        "    param_grid={\n",
        "        \"scaler\": [StandardScaler(), MinMaxScaler(), Normalizer(), MaxAbsScaler(), \"passthrough\"],\n",
        "        \"onehot\": [OneHotEncoder(), \"passthrough\"],\n",
        "        \"selector\"  : [VarianceThreshold(), \"passthrough\"],\n",
        "        'estimator': [ridge_param_grid, kn_param_grid, dt_param_grid, bagging_param_grid, random_forest_param_grid],\n",
        "    },\n",
        "    scoring = 'balanced_accuracy',\n",
        "    cv = 3,\n",
        "    return_train_score = True\n",
        ")\n",
        "#fit on training data\n",
        "grid.fit(x_train, y_train)\n",
        "\n",
        "#score over test\n",
        "print('Training set score: ' + str(grid.score(x_train, y_train)))\n",
        "print('Test set score: ' + str(grid.score(x_test, y_test)))\n",
        "#10-fold cv over training set\n",
        "cv_results = cross_validate(\n",
        "        grid, x_train, y_train, cv=10, return_estimator=True, scoring = \"balanced_accuracy\"\n",
        "    )\n",
        "cv_results = pd.DataFrame(cv_results)\n",
        "cv_test_scores = cv_results[\"test_score\"]\n",
        "#display results\n",
        "print(\n",
        "        \"Generalization score with hyperparameters tuning:\\n\"\n",
        "        f\"{cv_test_scores.mean():.3f} ± {cv_test_scores.std():.3f}\"\n",
        "    )\n",
        "#display best hyperparameter configuration\n",
        "print(\"Best Score: \", grid.best_score_)\n",
        "print(\"Best Params: \", grid.best_params_)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bqFt3YeWaeiF",
        "outputId": "d4bb2896-69ba-428a-e82d-7d2b29ace728"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: \n",
            "240 fits failed out of a total of 400.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "80 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1152, in wrapper\n",
            "    return fit_method(estimator, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 1435, in fit\n",
            "    super().fit(X, Y, sample_weight=sample_weight)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 823, in fit\n",
            "    raise ValueError(\n",
            "ValueError: solver='svd' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "80 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1152, in wrapper\n",
            "    return fit_method(estimator, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 1435, in fit\n",
            "    super().fit(X, Y, sample_weight=sample_weight)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 823, in fit\n",
            "    raise ValueError(\n",
            "ValueError: solver='cholesky' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "80 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1152, in wrapper\n",
            "    return fit_method(estimator, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 1435, in fit\n",
            "    super().fit(X, Y, sample_weight=sample_weight)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 823, in fit\n",
            "    raise ValueError(\n",
            "ValueError: solver='saga' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan\n",
            "        nan        nan 0.53400069 0.53400069 0.53400069 0.53633987\n",
            "        nan        nan        nan        nan 0.53400069 0.53517716\n",
            " 0.53398693 0.55750946        nan        nan        nan        nan\n",
            "        nan        nan        nan        nan 0.53752322 0.53752322\n",
            " 0.53752322 0.54222222        nan        nan        nan        nan\n",
            " 0.53752322 0.53752322 0.53986928 0.55750946        nan        nan\n",
            "        nan        nan        nan        nan        nan        nan\n",
            " 0.54926729 0.54926729 0.54926729 0.55162023        nan        nan\n",
            "        nan        nan 0.54926729 0.54809082 0.55396629 0.56573099\n",
            "        nan        nan        nan        nan        nan        nan\n",
            "        nan        nan 0.55515652 0.55515652 0.55515652 0.56101823\n",
            "        nan        nan        nan        nan 0.55515652 0.55515652\n",
            " 0.55750258 0.56221534]\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
            "    scores = scorer(estimator, X_test, y_test)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 266, in __call__\n",
            "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 353, in _score\n",
            "    y_pred = method_caller(estimator, \"predict\", X)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 86, in _cached_call\n",
            "    result, _ = _get_response_values(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_response.py\", line 194, in _get_response_values\n",
            "    y_pred = prediction_method(X)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py\", line 514, in predict\n",
            "    Xt = transform.transform(Xt)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
            "    data_to_wrap = f(self, X, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
            "    X_int, X_mask = self._transform(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
            "    raise ValueError(msg)\n",
            "ValueError: Found unknown categories [1.6499419996212068, 2.792535304287022, 2.9729447734447816, 3.0932177528832887, 4.0554015883913435] in column 0 during transform\n",
            "\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: \n",
            "240 fits failed out of a total of 400.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "80 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1152, in wrapper\n",
            "    return fit_method(estimator, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 1435, in fit\n",
            "    super().fit(X, Y, sample_weight=sample_weight)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 823, in fit\n",
            "    raise ValueError(\n",
            "ValueError: solver='svd' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "80 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1152, in wrapper\n",
            "    return fit_method(estimator, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 1435, in fit\n",
            "    super().fit(X, Y, sample_weight=sample_weight)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 823, in fit\n",
            "    raise ValueError(\n",
            "ValueError: solver='cholesky' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "80 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1152, in wrapper\n",
            "    return fit_method(estimator, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 1435, in fit\n",
            "    super().fit(X, Y, sample_weight=sample_weight)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_ridge.py\", line 823, in fit\n",
            "    raise ValueError(\n",
            "ValueError: solver='saga' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan\n",
            "        nan        nan 0.52403853 0.52403853 0.52404541 0.52052976\n",
            "        nan        nan        nan        nan 0.52403853 0.52286894\n",
            " 0.52052288 0.53460612        nan        nan        nan        nan\n",
            "        nan        nan        nan        nan 0.520516   0.520516\n",
            " 0.52168559 0.52989336        nan        nan        nan        nan\n",
            " 0.520516   0.520516   0.52402477 0.53109735        nan        nan\n",
            "        nan        nan        nan        nan        nan        nan\n",
            " 0.52287582 0.52287582 0.52287582 0.52874441        nan        nan\n",
            "        nan        nan 0.52287582 0.52170623 0.52170623 0.54164431\n",
            "        nan        nan        nan        nan        nan        nan\n",
            "        nan        nan 0.5275473  0.5275473  0.52990024 0.53108359\n",
            "        nan        nan        nan        nan 0.5275473  0.5275473\n",
            " 0.52990024 0.54165807]\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
            "    scores = scorer(estimator, X_test, y_test)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 266, in __call__\n",
            "    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 353, in _score\n",
            "    y_pred = method_caller(estimator, \"predict\", X)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 86, in _cached_call\n",
            "    result, _ = _get_response_values(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_response.py\", line 194, in _get_response_values\n",
            "    y_pred = prediction_method(X)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py\", line 514, in predict\n",
            "    Xt = transform.transform(Xt)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
            "    data_to_wrap = f(self, X, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
            "    X_int, X_mask = self._transform(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
            "    raise ValueError(msg)\n",
            "ValueError: Found unknown categories [-2.175848726880045, -1.5418708799615755, 3.1265114473471494, 4.106295392584783, 4.336832791464226] in column 0 during transform\n",
            "\n",
            "  warnings.warn(\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(grid.param_grid[\"estimator\"][1].best_params_)"
      ],
      "metadata": {
        "id": "fm8YBsKbtC0W"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "IHN-gewj5A9U"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}